### ISSUE TITLE
PVA Gateway - Error while processing cmd 0x0d: Must provide prototype

### ISSUE THREAD

**Issue by Monarda** [mdavidsaver/p4p#104]
We're running PVA Gateway (version 4.1.5) as a service in a read-only configuration on a pair of Linux servers using systemd. Today I found that one PVA Gateway was working and the other was not. Checking the logs shows the following errors on the service that was not working:

```
Apr 25 09:18:14 perses pvagw_ro[2547661]: 2023-04-25T09:18:14.576143860 ERR pvxs.tcp.io connection to Client 130.246.161.40:52211 closed with socket error 104 : Connection reset by peer
Apr 25 09:34:04 perses pvagw_ro[2547661]: 2023-04-25T09:34:04.629178967 CRIT pvxs.tcp.io Client Error while processing cmd 0x0d: Must provide prototype
Apr 25 09:34:04 perses pvagw_ro[2547661]: Dumping a stack trace of thread 'PVXTCP':
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f9558fbcb6b]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../epicscorelibs/lib/libCom.so.7.0.7.99.0(epicsStackTrace+0x4b)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f95592a9705]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs6detail11_log_printfEjPKcz+0xa5)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f955926bce6]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl8ConnBase7bevReadEv+0x696)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f9559276279]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl10ServerConn7bevReadEv+0x9)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f955926c031]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl8ConnBase8bevReadSEP11buffereventPv+0x21)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f95587cd432]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/./libevent_core.so.2.2.0(bufferevent_run_deferred_callbacks_locked+0x82)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f95587c6db6]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/./libevent_core.so.2.2.0(event_process_active_single_queue.isra.33+0x446)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f95587c775f]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/./libevent_core.so.2.2.0(event_base_loop+0x49f)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f95592e1810]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl6evbase3Pvt3runEv+0x160)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f9558fd5f69]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../epicscorelibs/lib/libCom.so.7.0.7.99.0(epicsThreadCallEntryPoint+0x69)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f9558fc18da]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../epicscorelibs/lib/libCom.so.7.0.7.99.0(start_routine+0xda)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f956b7591cf]: /lib64/libpthread.so.0(start_thread+0xef)
Apr 25 09:34:04 perses pvagw_ro[2547661]: [    0x7f956ac3ae73]: /lib64/libc.so.6(clone+0x43)
Apr 25 09:35:32 perses pvagw_ro[2547661]: 2023-04-25T09:35:32.656107078 CRIT pvxs.tcp.io Client Error while processing cmd 0x0d: Must provide prototype
Apr 25 09:35:32 perses pvagw_ro[2547661]: Dumping a stack trace of thread 'PVXTCP':
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f9558fbcb6b]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../epicscorelibs/lib/libCom.so.7.0.7.99.0(epicsStackTrace+0x4b)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f95592a9705]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs6detail11_log_printfEjPKcz+0xa5)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f955926bce6]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl8ConnBase7bevReadEv+0x696)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f9559276279]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl10ServerConn7bevReadEv+0x9)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f955926c031]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl8ConnBase8bevReadSEP11buffereventPv+0x21)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f95587cd432]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/./libevent_core.so.2.2.0(bufferevent_run_deferred_callbacks_locked+0x82)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f95587c6db6]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/./libevent_core.so.2.2.0(event_process_active_single_queue.isra.33+0x446)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f95587c775f]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/./libevent_core.so.2.2.0(event_base_loop+0x49f)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f95592e1810]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../pvxslibs/lib/libpvxs.so.1.1(_ZN4pvxs4impl6evbase3Pvt3runEv+0x160)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f9558fd5f69]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../epicscorelibs/lib/libCom.so.7.0.7.99.0(epicsThreadCallEntryPoint+0x69)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f9558fc18da]: /opt/pvagateway/venv/lib64/python3.6/site-packages/p4p/../epicscorelibs/lib/libCom.so.7.0.7.99.0(start_routine+0xda)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f956b7591cf]: /lib64/libpthread.so.0(start_thread+0xef)
Apr 25 09:35:32 perses pvagw_ro[2547661]: [    0x7f956ac3ae73]: /lib64/libc.so.6(clone+0x43)
```

The PVA Gateway service needed to be manually restarted and then came back fine. Which suggests it didn't fully crash in response to the output stack trace but also wasn't working properly.

Note that we're connecting to these services exclusively using TCP only discovery (EPICS_PVA_NAME_SERVERS) from Phoebus, and on a non-standard port (7075/tcp).

**Comment by ttkorhonen** [comment]
We (ESS) have seen a similar issue a few times recently. The gateway has been stable but now we had a few crashes in a short period of time. For comparison, our stack trace:
`maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: ERROR:p4p.gw:Error during periodic sweep
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: Traceback (most recent call last):
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: File "/opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/gw.py", line 723, in run
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: self.stats.update_stats(period)
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: File "/opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/gw.py", line 328, in update_stats
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: C.executemany('INSERT INTO ds VALUES (?,?,?,?,?,?,?,?)', _gw.Server_report(server, norm))
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: File "_gw.pyx", line 319, in p4p._gw.Server_report
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 10: invalid continuation byte
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: 2023-05-22T17:05:14.543771947 CRIT pvxs.tcp.io Client Error while processing cmd 0x0d: Must provide prototype
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: Dumping a stack trace of thread 'PVXTCP':
maj 22 17:05:14 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f15350513]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../../epics/lib/linux-x86_64/libCom.so.3.21.0(epicsStackTrace+0x53)
maj 22 17:05:15 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f151e5f61]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../libpvxs.so.0.2(_ZN4pvxs6detail11_log_printfEjPKcz+0xa1)
maj 22 17:05:15 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f1525ced8]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../libpvxs.so.0.2(_ZN4pvxs4impl8ConnBase7bevReadEv+0x7e8)
maj 22 17:05:15 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f1526d669]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../libpvxs.so.0.2(_ZN4pvxs4impl10ServerConn7bevReadEv+0x9)
maj 22 17:05:15 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f1525d30f]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../libpvxs.so.0.2(_ZN4pvxs4impl8ConnBase8bevReadSEP11buffereventPv+0x1f)
maj 22 17:05:15 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f14f6c64c]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../.././libevent_core-2.1.so.6(bufferevent_run_deferred_callbacks_locked+0x7c)
maj 22 17:05:16 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f14f75bee]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../.././libevent_core-2.1.so.6(event_process_active_single_queue.isra.0+0x2be)
maj 22 17:05:16 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f14f7635f]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../.././libevent_core-2.1.so.6(event_base_loop+0x3cf)
maj 22 17:05:16 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f15241f3b]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../libpvxs.so.0.2(_ZN4pvxs4impl6evbase3Pvt3runEv+0x15b)
maj 22 17:05:16 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f15345609]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../../epics/lib/linux-x86_64/libCom.so.3.21.0(epicsThreadCallEntryPoint+0x39)
maj 22 17:05:17 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f1534a350]: /opt/conda/envs/pva-gateway/lib/python3.7/site-packages/p4p/../../../../epics/lib/linux-x86_64/libCom.so.3.21.0(start_routine+0xe0)
maj 22 17:05:17 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f1c6f0e65]: /lib64/libpthread.so.0(start_thread+0xc5)
maj 22 17:05:17 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: [    0x7f0f1bb0888d]: /lib64/libc.so.6(clone+0x6d)
maj 22 17:05:17 idmz-ro-epics-gw-tn.esss.lu.se pvagw[3472]: 2023-05-22T17:05:17.761085412 ERR pvxs.client.io Server 172.16.107.38:5075 uses non-existent IOID 268453813.  Ignoring...
`

**Comment by mdavidsaver** [comment]
It looks like this may be a ~straightforward logic error in the gateway code.  The exception comes from:

https://github.com/mdavidsaver/pvxs/blob/13f7cd724d86e4e5b735198e3b05ff301d12f502/src/servermon.cpp#L368-L371

Which I think is coming through

https://github.com/mdavidsaver/p4p/blob/0f34c6a2b18eb68ec40e3ce31be52a9eed04f4ca/src/pvxs_gw.cpp#L625

Where `sub->current` can indeed be "empty" for a brief time between monitor op. creation, and arrival of the first update.  So I think the triggering situation is a race between creation of the first and second subscription.  That is, if the second subscription is created while the first subscription is still awaiting an initial update.

**Comment by mdavidsaver** [comment]
#106 may fix this issue.
