### ISSUE TITLE
PV List statement ".* DENY" voids all following ALLOW statements

### ISSUE THREAD

**Issue by drm-slac** [mdavidsaver/p4p#114]
Documentation states:
> ...a line .* DENY intended to block all names not specifically allowed must be placed at the top of the file.
But adding such a line causes all subsequent ALLOW statements to fail.

**Comment by mdavidsaver** [comment]
Could you provide some context for this discussion?  Is this about the `EVALUATION ORDER` or something else?

As I recall, I was working from the [ca-gateway manual](https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/Gateway/Gateway.html).  I deliberately did not support `EVALUATION ORDER DENY, ALLOW`.  Additionally, it is entirely possible that other unintentional differences exist.

When discussing the PV list mechanism, it would help me if you could provide concrete example(s) of a list file and PV name when discussing what you expect to happen.  Ideally, these would be worked into unit tests:

https://github.com/mdavidsaver/p4p/blob/e2eb24e709466594c397d8c97e58c107735cfde6/src/p4p/test/test_asLib.py#L17-L18

fyi. `p4p.gw` has a "status" PV [`<statusprefix>asTest`](https://mdavidsaver.github.io/p4p/gw.html#status-pvs) to probe the PV list / ACF policy for arbitrary PV, user, host, and/or roles.

**Comment by drm-slac** [comment]
Hi Michael, the PVA Gateway documentation (p4p v4.1.7) under the PV List File heading, says:
Syntax is line based. Order of precedence is DENY over ALLOW and last to first.
So a line .* DENY intended to block all names not specifically allowed must be placed at the top of the file.

We have a pvlist file containing
^[A-Za-z0-9]+:GUNB:.*    ALLOW
^[A-Za-z0-9]+:SPH:.*     ALLOW
^[A-Za-z0-9]+:SYS0:.*    ALLOW
The PVs indicated by the REs are all readable, and those that don’t match are not.
But after adding the DENY statement:
.* DENY
^[A-Za-z0-9]+:GUNB:.*    ALLOW
^[A-Za-z0-9]+:SPH:.*     ALLOW
^[A-Za-z0-9]+:SYS0:.*    ALLOW
No PVs are accessible.  This isn’t terribly important since DENY is the default.  Perhaps this is just a documentation thing..?
I initially added this as an issue because I was looking at other problems on our side and didn’t want to forget about it.  I didn’t have a chance to look at that part of the code.

Incidentally, regarding the asTest PV, I’ve written a small C++ program to access that and other diagnostic PVs as well, it’s proving to be useful here so far.

cheers
-doug


From: mdavidsaver ***@***.***>
Date: Monday, August 7, 2023 at 3:02 PM
To: mdavidsaver/p4p ***@***.***>
Cc: Murray, Doug ***@***.***>, Author ***@***.***>
Subject: Re: [mdavidsaver/p4p] PV List statement ".* DENY" voids all following ALLOW statements (Issue #114)

Could you provide some context for this discussion? Is this about the EVALUATION ORDER or something else?

As I recall, I was working from the ca-gateway manual<https://epics.anl.gov/EpicsDocumentation/ExtensionsManuals/Gateway/Gateway.html>. I deliberately did not support EVALUATION ORDER DENY, ALLOW. Additionally, it is entirely possible that other unintentional differences exist.

When discussing the PV list mechanism, it would help me if you could provide concrete example(s) of a list file and PV name when discussing what you expect to happen. Ideally, these would be worked into unit tests:

https://github.com/mdavidsaver/p4p/blob/e2eb24e709466594c397d8c97e58c107735cfde6/src/p4p/test/test_asLib.py#L17-L18

fyi. p4p.gw has a "status" PV <statusprefix>asTest<https://mdavidsaver.github.io/p4p/gw.html#status-pvs> to probe the PV list / ACF policy for arbitrary PV, user, host, and/or roles.

**Comment by ralphlange** [comment]
I think this issue can be closed.

The behavior that Doug expects is what the CA Gateway does for "EVALUATION ORDER DENY, ALLOW", which is explicitly not supported by the PVA Gateway.
From the CA Gateway documentation (example pvlist file):
```
#  ORDER:
#  This will set the evaluation order that is used when a client requests
#  a PV. Setting this to "DENY, ALLOW" will allow access to a PV name that matches
#  both a DENY and an ALLOW pattern. "ALLOW, DENY" will make a DENY override an ALLOW
#  for the same variable. (This is the default.)
```

The PVA Gateway (4.1.12) documentation says:

> The order in which regular expressions are matched is that all DENY statements are considered before any ALLOW/ALIAS statements (regardless of lexical order). PV names which do not match any statement are DENYed.
> 
> When a PV name matches more than one ALLOW/ALIAS statements, lexical order is used. The last match will have effect.

This is clear and concise enough.
Note: The term "lexical order" is misleading if not wrong and should be replaced by "order of lines".
