### ISSUE TITLE
Put mbbo writes don't work with wait=True

### ISSUE THREAD

**Issue by coretl** [mdavidsaver/p4p#123]
With the IOC (QSRV2):

```python
from softioc import asyncio_dispatcher, builder, softioc

mbbo = builder.mbbOut("TESTENUM", "ONE", "TWO", "THREE", on_update=print)
ao = builder.aOut("TESTAI", on_update=print)
builder.LoadDatabase()
softioc.iocInit(asyncio_dispatcher.AsyncioDispatcher())
softioc.interactive_ioc(globals())
```

Putting ai with wait=True works, but mbbo fails:

```python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from p4p.client.thread import Context
>>> c = Context()
>>> c.get("TESTAI")
0.0
>>> c.put("TESTAI", 1, wait=True)
>>> c.get("TESTAI")
1.0
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> c.put("TESTENUM", "TWO", wait=True)
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> c.put("TESTENUM", 2, wait=True)
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> c.put("TESTENUM", "TWO")
>>> c.get("TESTENUM")
ntenum(1, TWO)
```

Versions:
- p4p 4.1.10
- pvxslibs                      1.2.3
- epicscorelibs                 7.0.7.99.0.2
- softioc                       4.4.0

Any ideas?

**Comment by mdavidsaver** [comment]
Was the quoted session "interactive"?  Should I imagine a `sleep(1)` between each line while someone is typing?

> Any ideas?

Cross-check with cothread/catools to see if this is a database issue or QSRV/PVA issue.

Have each `put()` send a different value, to clarify if a put has no effect, or a delayed effect.

Check the fourth combination `c.put("TESTENUM", 2)`.

**Comment by coretl** [comment]
> Was the quoted session "interactive"? Should I imagine a `sleep(1)` between each line while someone is typing?

Yes
 
> Cross-check with cothread/catools to see if this is a database issue or QSRV/PVA issue.

This works (enums are 0: ONE, 1: TWO, 2: THREE)

```python
>>> caput("TESTENUM", "THREE", wait=True)
ca_nothing('TESTENUM', 1)
>>> caget("TESTENUM")
2
>>> caput("TESTENUM", "TWO", wait=True)
ca_nothing('TESTENUM', 1)
>>> caget("TESTENUM")
1
```
Commandline pvput also works:
```
$ pvput -w 1 TESTENUM TWO
Old : 2023-09-13 13:27:29.157  (2) THREE
New : 2023-09-13 13:27:32.322  (1) TWO
```

> Have each `put()` send a different value, to clarify if a put has no effect, or a delayed effect.

```python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from p4p.client.thread import Context
>>> c = Context()
>>> c.put("TESTENUM", "TWO", wait=True)
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> c.put("TESTENUM", "THREE", wait=True)
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> 
```

Don't think it is delayed, without `wait=True` (or on an ai record, or using cothread) then the `on_update` callback fires on the IOC side. With p4p (and only putting to an mbbo with wait=True) then nothing fires on the IOC side.


> Check the fourth combination `c.put("TESTENUM", 2)`.

Same thing, works (and callback fires) without `wait`, and doesn't work with `wait=True`

**Comment by coretl** [comment]
Actually, I think this is server side, it works on pythonSoftIOC 4.3.0 (which was QSRV), but fails on pythonSoftIOC 4.4.0 (which is QSRV2). I'll try removing pythonSoftIOC from the equation and post back...

**Comment by coretl** [comment]
This reproduces it with just pvxslibs:

```python
import ctypes
import os

import pvxslibs.path
from epicscorelibs import ioc
from setuptools_dso.runtime import find_dso

pvxsIoc = ctypes.CDLL(find_dso("pvxslibs.lib.pvxsIoc"), ctypes.RTLD_GLOBAL)
os.environ.setdefault("PVXS_QSRV_ENABLE", "YES")

orig_dbld = ioc.dbLoadDatabase


def dbLoadDatabase(dbd, dbdpath, substitutions):
    if dbd == b"qsrv.dbd":
        orig_dbld(b"pvxsIoc.dbd", pvxslibs.path.dbd_path.encode(), None)
    elif dbd == b"PVAServerRegister.dbd":
        pass
    else:
        orig_dbld(dbd, dbdpath, substitutions)


ioc.dbLoadDatabase = dbLoadDatabase

if __name__ == "__main__":
    ioc.main()
```
```
record(mbbo, "TESTENUM") {
    field(ZRST, "ONE")
    field(ONST, "TWO")
    field(TWST, "THREE")
}
```
```python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from p4p.client.thread import Context
>>> c = Context()
>>> c.put("TESTENUM", "THREE", wait=True)
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> c.put("TESTENUM", "THREE", wait=True)
>>> c.get("TESTENUM")
ntenum(0, ONE)
>>> c.put("TESTENUM", "THREE")
>>> c.get("TESTENUM")
ntenum(2, THREE)
```

**Comment by coretl** [comment]
@mdavidsaver shall we go on digging into the IOC side? I guess this should be transferred to the pvxslibs repo...

**Comment by mdavidsaver** [comment]
This issue should be fixed by mdavidsaver/pvxs@9ccd7b50ab4fb59e59176fe45339cbba2cfd9e5e .

**Comment by jsouter** [comment]
Have tested this on my end and can confirm the above fix has worked.
`Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from p4p.client.thread import Context
>>> c = Context()
>>> c.put("TESTENUM", "THREE", wait=True)
>>> c.get("TESTENUM")
ntenum(2, THREE)
>>> c.put("TESTENUM", "TWO", wait=False)
>>> c.get("TESTENUM")
ntenum(1, TWO)`

**Comment by mdavidsaver** [comment]
> ... Are you planning a non-alpha release ...

I had hoped to do a whole set of releases (epicscorelibs, pvxslibs, and p4p).  However, things are not working out.  I have "yanked" epicscorelibs `7.0.7.99.1.0`.  This update of epicscorelibs was mainly motivated by my fix for https://github.com/epics-base/epics-base/issues/423.  However, I have found a further issue with that.  So I am going to abort on the epicscorelibs update until I can fix my fix.

My plan at the moment is to also "yank" 7.0.7.99.1.0a1, as well as the pvxslibs and p4p pre-release wheels which depend on it.  Then I will push out pvxslibs and p4p releases built against the current 7.0.7.99.0.2 .

However, it is getting late for me, so I will wait until tomorrow morning my time before doing anything more with pypi.org.  Please let me know if you think what I describe would break something with your softioc wheels.

**Comment by coretl** [comment]
> Please let me know if you think what I describe would break something with your softioc wheels.

That all sounds fine for me, as long as the pvxslibs fix for this issue makes it into the release then that's all I need

**Comment by mdavidsaver** [comment]
`pvxslibs==1.2.4` and `p4p==4.1.11` are up.  Both are built against `epicscorelibs==7.0.7.99.0.2`.  The associated pre-release builds are "yank"ed.

**Comment by coretl** [comment]
Thanks, this fixes it for us
