### ISSUE TITLE
PVA Server to dynamically host PVA variables

### ISSUE THREAD

**Issue by weninc** [mdavidsaver/p4p#13]
Is there a way to run a PVA server that can dynamically host PVA variables created from python?
Looking for something similar to the Example RPC Provider from the documentation but for just hosting PVA variables without running a softIocPVA.

**Comment by mdavidsaver** [comment]
Not yet.  Work on this feature is getting started.

**Comment by mdavidsaver** [comment]
see #17

**Comment by weninc** [comment]
We quickly tested hosting dynamic PVs with your recent changes and it seems to work fine.
Thanks a lot and I guess I can close this issue.
