### ISSUE TITLE
Value.type() fails if the structure has a type field

### ISSUE THREAD

**Issue by thomascobb** [mdavidsaver/p4p#18]
For example, if v is:

```
malcolm:core/Table:1.0 value
      string[] name []
      string[] filename []
      string[] type []
      int[] rank []
      string[] path []
      string[] uniqueid []
```

v.type() fails with ```TypeError: 'list' object is not callable```

**Comment by mdavidsaver** [comment]
I thought that ```PyTypeObject::tp_getattro``` behaved like ```object.__getattr__```, but it actually behaves like ```object.__getattribute__```.  So the 'type' field was hiding the 'type()' method.  130b1da9f65fa40c5707ada2e68ac8d99b385ea2 reverses this.
