### ISSUE TITLE
NTEnum Type is having issues

### ISSUE THREAD

**Issue by tynanford** [mdavidsaver/p4p#25]
I was trying to use the NTEnum type to create a SharedPV and I could not because it does not have an unwrap method.

I tried to implement the unwrap method myself and things started to get messy so I have created this issue and will use different types for now. 

If this helps, here is what I ran into. I set up the wrap method to take in a value of type dictionary of this form: { 'index': int, 'choices': [strings] }. Here is what my enum.py file looked like.

```
class ntenum(ntwrappercommon, dict):
    """
    Augmented dictionary with additional attributes

    * .severity
    * .status
    * .timestamp - Seconds since 1 Jan 1970 UTC as a float
    * .raw_stamp - A tuple (seconds, nanoseconds)
    * .raw - The underlying :py:class:`p4p.Value`.
    """
    
    def _store(self, value):        
        ntwrappercommon._store(self, value)

        return self


class NTEnum(object):
    """Describes a string selected from among a list of possible choices.  Stored internally as an integer
    """
    Value = Value
    ntenum = ntenum
    
    @staticmethod
    def buildType(extra=[], display=False, control=False, valueAlarm=False):
        F = [
            ('value', ('S', 'enum_t', [
                ('index', 'i'),
                ('choices', 'as'),
            ])),
            ('alarm', alarm),
            ('timeStamp', timeStamp),
        ]
        _metaHelper(F, 'i', display=display, control=control, valueAlarm=valueAlarm)
        F.extend(extra)
        return Type(id="epics:nt/NTEnum:1.0", spec=F)

    def __init__(self, **kws):      
        self.type = self.buildType(**kws)

    def wrap(self, value):
        """Pack python value into Value
        """        
        # will take in dictionary {index: int, choices: [strings]}
        
        S, NS = divmod(time.time(), 1.0)
        
        value = {'index': value['index'], 'choices': value['choices']}

        return Value(self.type, {
            'value': value,
            'timeStamp': {
                'secondsPastEpoch': S,
                'nanoseconds': NS * 1e9,
            },
        })

    @classmethod
    def unwrap(klass, value):
        """Unpack a Value into an augmented python type (selected from the 'value' field)
        """

        return klass.ntenum(value.value)._store(value)
```

Here is my code to create the enum PV.

```
class EnumHandler:
    def put(arg1, pv, op):
        pv.post(op.value())
        op.done()  

provider = StaticProvider('arbitrary')

my_py_enum_structure = {'index': 0, 'choices': ['choice1', 'choice2', 'choice3']}

sampleEnumPV = SharedPV(handler=EnumHandler(), nt=NTEnum(), initial=my_py_enum_structure)
provider.add('sample:enum', sampleEnumPV)

Server.forever(providers=[provider])
```

This code created the sample:enum PV correctly. 
```
enum_t value
    int index 0
    string[] choices ["choice1", "choice2", "choice3"]
```

The issue was when I connected the sample:enum PV to a combo box in CS Studio and tried to select a different value. The put handler would only have the index value. The 'choices' array was empty. So after the first put, the choices array data was lost.

```
enum_t value
    int index 1
    string[] choices []
```

**Comment by mdavidsaver** [comment]
I know the current handling of NTEnum is a weak point.  I'd like to use `enum.IntEnum` as a representation, but don't want be py3 only (yet).  As I'm undecided on what to, and input like yours is helpful.

> So after the first put, the choices array data was lost.

Let's skip the `ntenum` part for the moment as it seems likely that there is an external problem.

rewriting your example as:

```py
import logging
from p4p.server import StaticProvider, Server
from p4p.server.thread import SharedPV
from p4p.nt import NTEnum
logging.basicConfig(level=logging.DEBUG)
class EnumHandler:
    def put(arg1, pv, op):
        print("PUT", op.value().changedSet())
        pv.post(op.value())
        op.done()  

provider = StaticProvider('arbitrary')

initial = NTEnum.buildType()()
initial.value.index = 0
initial.value.choices = ['choice1', 'choice2', 'choice3']

sampleEnumPV = SharedPV(handler=EnumHandler(), initial=initial)
provider.add('sample:enum', sampleEnumPV)

Server.forever(providers=[provider])
```

I then run (using `pvput` from Base 7.0.2)

```
$ pvput sample:enum choice2`
Old : <undefined>              (0) choice1
New : <undefined>              (1) choice2
```

This works as you would expect.  Concurrently server prints:

```
...
('PUT', set([u'value.index']))
```

Showing that the Put operation included only the `value.index` field and __not__ `value.choices`.

Can you try this with your cs-studio version?

I suspect that it will either show either that `value.choices` __is__ being sent explicitly, or more likely that the whole `value` sub-structure is sent.  Either of these is would be a cs-studio bug.

**Comment by tynanford** [comment]
I tested your example code (still with my enum.py edits) on cs-studio and everything is working as expected.

When I change the combo box value to choice2, only the index value is included.
```
PUT {'value.index'}
```
And it correctly changes the PV and keeps the combo box items on a refresh in cs-studio.
```
$ pvget sample:enum
sample:enum            choice2
```

So it appears the way I was creating the SharedPV was incorrect.

**Comment by mdavidsaver** [comment]
In P4P==3.1.0
