### ISSUE TITLE
Is it possible to support the ca protocol?

### ISSUE THREAD

**Issue by willrogers** [mdavidsaver/p4p#29]
You can create `pva` context but not a `ca` context.

In some places in the EPICS documentation it says that PVAccess supports both the CA and the PVA protocols.

Would it be easy or difficult to provide a `ca` context in p4p?

**Comment by mdavidsaver** [comment]
It would not be technically difficult to allow `Context('ca')` to be used.  There would be a disclaimer given my history of problems with the caProvider code.  My recommendation is continued use cothread, or any of the other libca bindings.

It also wouldn't be difficult to add a wrapper around cothread.catools to look like `p4p.client.cothread.Context`.

**Comment by willrogers** [comment]
OK, I will bear that in mind. Thanks.
