### ISSUE TITLE
ValueError on NTTable build example

### ISSUE THREAD

**Issue by arkilic** [mdavidsaver/p4p#3]
`T=NTTable(columns=[('A', 'ai'), ('B', 'as')])` seems like a typo in the docs. This should be:

`T=NTTable.buildType(columns=[('A', 'ai'), ('B', 'as')])`

**Comment by mdavidsaver** [comment]
The original should is what I intended.  It should as seen in test_nt.py

https://github.com/mdavidsaver/p4p/blob/316ca75f0573c697b8f983f7d7456239a636396d/src/p4p/test/test_nt.py#L82
