### ISSUE TITLE
Seg fault at Python exit

### ISSUE THREAD

**Issue by thomascobb** [mdavidsaver/p4p#34]
My unit tests for pymalcolm have been testing p4p for a long time with no seg faults, but today I got a failed build with a seg fault:

2019-04-03T11:03:18.266 unknown exception caught while in receiveThread at modules/pvAccess/src/remote/codec.cpp:1148.
FATAL: exception not rethrown

The versions:
p4p-3.2.0
epicscorelibs-7.0.2.99.0.0

More details (with backtrace):
https://travis-ci.org/dls-controls/pymalcolm/jobs/515133961#L2435

A second instance also seg faulted with a different error message:
https://travis-ci.org/dls-controls/pymalcolm/jobs/515184557#L2551

**Comment by mdavidsaver** [comment]
The failure mode is one which I recognize.  Calling PyGILState_*() functions during/after Py_Finalize().  I thought I was preventing this with a python atexit hook, but maybe not in all cases.

**Comment by mdavidsaver** [comment]
May be fixed by cc5bd62054a3839d38f2ac383679ee68763d9649.  Apparently my memory of having coordinated shutdown of servers was a false one.

**Comment by mdavidsaver** [comment]
If this doesn't fix the problem, then I'll go for a heavier solution of adding my own synchronization in all PVA callbacks.

**Comment by thomascobb** [comment]
Ok, I will update to use master and see if it fixes things. The problem takes a while to show up, so I'll let you know if it does...

**Comment by thomascobb** [comment]
This has not re-occurred, so hopefully this means it is fixed!
