### ISSUE TITLE
Invalid hostname in config file not handled properly

### ISSUE THREAD

**Issue by bhill-slac** [mdavidsaver/p4p#40]
If the config file defines a server w/ an invalid hostname (for example, mis-spelled), a PVA server is created for 0.0.0.0:5075.
This causes clients to see multiple connections to PVA searches, as they get a search response from their dedicated network adapter on the gateway machine plus each server w/ intf addr 0.0.0.0:5075.

Here's output from running verbose.   pscag1-cdsdev is an invalid hostname.

DEBUG:p4p.asLib:Recompute all
DEBUG:p4p.server:Starting Server isolated=False, {'conf': {'EPICS_PVAS_INTF_ADDR_LIST': 'pscag1-cdsdev', 'EPICS_PVAS_BEACON_ADDR_LIST': '134.79.165.255', 'EPICS_PVA_AUTO_ADDR_LIST': 'NO'}, 'useenv': False}
2019-08-06T21:38:39.665 Using dynamically assigned TCP port 58302.
INFO:__main__:Server config dev-server :
{'EPICS_PVAS_AUTO_BEACON_ADDR_LIST': 'NO',
 'EPICS_PVAS_BEACON_ADDR_LIST': '134.79.165.255',
 'EPICS_PVAS_BEACON_PERIOD': '15',
 'EPICS_PVAS_BROADCAST_PORT': '5076',
 'EPICS_PVAS_INTF_ADDR_LIST': '0.0.0.0:5075',
 'EPICS_PVAS_MAX_ARRAY_BYTES': '16384',
 'EPICS_PVAS_PROVIDER_NAMES': 'gwsts.dev-server gws.dev-server.theclient',
 'EPICS_PVAS_SERVER_PORT': '58302',
 'EPICS_PVA_ADDR_LIST': '134.79.165.255',
 'EPICS_PVA_AUTO_ADDR_LIST': 'NO',
 'EPICS_PVA_BEACON_PERIOD': '15',
 'EPICS_PVA_BROADCAST_PORT': '5076',
 'EPICS_PVA_MAX_ARRAY_BYTES': '16384',
 'EPICS_PVA_SERVER_PORT': '58302'}
INFO:__main__:Status PV: PVAG:CXI:asTest
INFO:__main__:Status PV: PVAG:CXI:cache

**Comment by mdavidsaver** [comment]
I think this was fixed long ago.
