### ISSUE TITLE
name 'unicode' is not defined

### ISSUE THREAD

**Issue by mdalesio** [mdavidsaver/p4p#6]
Running python 3.4 or 3.6

Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:47) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from p4p.client.thread import Context
>>> cntxt = Context('pva')
>>> cntxt.get('pv:0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/train/p4p/python3.4m/linux-x86_64/p4p/client/thread.py", line 202, in get
    singlepv = isinstance(name, (bytes, unicode))
NameError: name 'unicode' is not defined

**Comment by mdavidsaver** [comment]
Fixed with 1c5d3317d5ca5605722769c23021e177c51c3898
