### ISSUE TITLE
Need equivalent to EPICS_CAS_IGNORE_ADDR_LIST 

### ISSUE THREAD

**Issue by bhill-slac** [mdavidsaver/p4p#60]
Needed to avoid gateways inadvertently serving PVs from other gateways leading to duplicate PV paths for clients.
As PVA gateway traffic has increased, we're starting to see more of these duplicate PV warnings.
Here's the scenario:
Subnet A is served by PVA gateway A to other subnets.
Subnet B is served by PVA gateway B to other subnets.
...
Each gateway host has network adapters for each subnet, so PVA clients
on subnet A can read PVs from gateways B, C, D, ...

Thus, gateway A search requests to subnet A get picked up by gateway B, C, D, ... as their host machines also 
have adapters on subnet A so they can serve their PVs to clients on subnet A.

This doesn't happen w/ the CA gateways which use the same pvlist files because the CA gateway
supports EPICS_CAS_IGNORE_ADDR_LIST which we define to the list of gateway host adapters to
block unwanted double gateway hops.

**Comment by mdavidsaver** [comment]
At least for this situation, do you think it would be enough to add an option (config file or CLI) to explicit ignore hosts?

The mechanism would be the same as the `--no-ban-local` logic.

https://github.com/mdavidsaver/p4p/blob/de508a13edfd440470b5f2b97196278f61131c11/src/p4p/gw.py#L667

**Comment by bhill-slac** [comment]
That sounds like a good approach.  Perhaps something like an ignoreaddr field in the server configuration section of the json file.

**Comment by hhslepicka** [comment]
I will take a try at this issue and report back here.
