### ISSUE TITLE
GitHub isn't showing all your tags as releases

### ISSUE THREAD

**Issue by anjohnson** [mdavidsaver/p4p#64]
Hi Michael, You've applied 3 new tags to the p4p repo since version 3.4.2 last January, but I just noticed that GitHub's [Releases page](https://github.com/mdavidsaver/p4p/releases) isn't showing the newer ones as published releases. Version 3.4.2 also appears as the latest release in the right-hand column of the main repo page:
![image](https://user-images.githubusercontent.com/5453863/105229338-6ae34c80-5b29-11eb-895c-b103df34a9c4.png)

Thought you might want to take a look at that and update it sometime; if you make use of GitHub's release process at all it seems you have to continue to do so every time to keep the website's "Latest" badge up to date.

**Comment by mdavidsaver** [comment]
I think github will let me delete "release" for the two tags which I did mark.  This will hopefully then revert the releases pages to showing a list of tags.

**Comment by mdavidsaver** [comment]
Ok, it is done.

Also, is this just a question of notification for you?  Rather than taking a tar blob from github.com, I had assumed that release managers at large sites would start from a local git clone, with verification of a signed tag.

**Comment by anjohnson** [comment]
Thanks. Actually it wasn't notifications (yet), but IIRC you do have a pointer to the releases page in your doc's, and that seemed a bit confusing to not have the "latest" appear to be marked as that; the project was looking slightly abandoned before.
