### ISSUE TITLE
Multiple decorators

### ISSUE THREAD

**Issue by thomasms** [mdavidsaver/p4p#69]
Does it make sense to use multiple decorators for puts handlers?
I naively thought that it would support multiple decorators as shown below in the simple example, however, it will only work for the last decorator.

```python
from p4p.nt import NTScalar
from p4p.server import Server
from p4p.server.thread import SharedPV

pv1 = SharedPV(nt=NTScalar('d'), 
              initial=0.0)     
pv2 = SharedPV(nt=NTScalar('d'),
              initial=4.2) 
pv3 = SharedPV(nt=NTScalar('d'),
              initial=24.2)      

@pv1.put
@pv2.put
@pv3.put
def handleput(pv, op):
    print(f"You changed my value to: {op.value().raw['value']}, I used to be: {pv.current().raw['value']}")
    pv.post(op.value())
    op.done()
    
@pv2.onFirstConnect
@pv1.onFirstConnect
def handlefirst(pv):
    print(f"Connected to {pv} with value: {pv.current().raw['value']}")


Server.forever(providers=[
    {
        'p4p:pv1':pv1,
        'p4p:pv2':pv2,
        'p4p:pv3':pv3,
    }
])
```

Doing a `pvput` for `pv1` or `pv2` I get the following error:
```bash
Unexpected
Traceback (most recent call last):
  File "/home/user/dev/venvs/epics/lib/python3.8/site-packages/p4p/server/thread.py", line 20, in _on_queue
    M(*args)
TypeError: 'NoneType' object is not callable
```
but it works fine for `pv3`. 

I understand this may not be the intended way to use these decorators - is it not possible to link two different PVs to the same handler?

**Comment by mdavidsaver** [comment]
If you are able to test a change, please try changing:

https://github.com/mdavidsaver/p4p/blob/3dee1053ddbf319891119160672b547af9cf6bd8/src/p4p/server/raw.py#L233-L237

into this:

```py
 @property 
 def put(self): 
     def decorate(fn): 
         self._handler.put = fn 
         return fn  # <--- add
     return decorate 
```

**Comment by thomasms** [comment]
Yep, fixes the put decorator. Do you want me to make a pull request to fix this?

**Comment by mdavidsaver** [comment]
Don't both.  This is a simple enough change.  3f59f52
