### ISSUE TITLE
Question: how do separate contexts work?

### ISSUE THREAD

**Issue by mattclarke** [mdavidsaver/p4p#71]
If I have two PVs and use a different context for both, are they completely separate all the way down the stack or do they eventually use the same instance of the underlying PVA library?

Sorry, if the question isn't very clear :D

**Comment by mdavidsaver** [comment]
Client `Context`s are largely independent, with different threads and sockets.  There is overlap only in potentially sharing of socket(s) used to receive UDP search request and beacon traffic on the well known port (eg. 5076).  `Context`s will never shared TCP connections, nor UDP search results.

**Comment by mattclarke** [comment]
Thank you!
