### ISSUE TITLE
p4p does not start

### ISSUE THREAD

**Issue by mrkraimer** [mdavidsaver/p4p#72]
I recently installed the latest version of fedora (release 34)
I  did install p4p

    mrk> pip check p4p
    No broken requirements found.
    mrk> pip show p4p
    Name: p4p
    Version: 3.5.3
    Summary: Python interface to PVAccess protocol client
    Home-page: https://mdavidsaver.github.io/p4p
    Author: Michael Davidsaver
    Author-email: mdavidsaver@gmail.com
    License: BSD
    Location: /usr/local/lib64/python3.9/site-packages
    Requires: numpy, nose, ply, epicscorelibs

But 

    mrk> python
    Python 3.9.5 (default, May 14 2021, 00:00:00) 
    [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)] on linux
    >>> import p4p
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib64/python3.9/site-packages/p4p/__init__.py", line 11, in <module>
        from .wrapper import Value, Type
      File "/usr/local/lib64/python3.9/site-packages/p4p/wrapper.py", line 5, in <module>
        from ._p4p import TypeBase, ValueBase
    ImportError: /usr/local/lib64/python3.9/site-packages/p4p/_p4p.cpython-39-x86_64-linux-gnu.so: undefined symbol: 
    _ZN5epics8pvAccess20ConfigurationBuilder4_addERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_

What am I missing?

**Comment by mdavidsaver** [comment]
Ah, you have python 3.9.  Right now I have a 3.9 build of the `epicscorelibs` dependency uploaded to `pypi.org`, but not `p4p` itself.  So the local build of `p4p` is using a different GCC version with a different c++ ABI.  This doesn't work so well.  I'll correct this.

For the time being try:

```sh
python -m pip uninstall p4p
python -m pip uninstall epicscorelibs
python -m pip install --no-binary epicscorelibs --no-binary p4p -v p4p
python -m nose -v p4p
```

It looks like you've installed under `/usr/local`, so you may need `sudo`.  fyi. install under `$HOME/.local/` should work just the same.

cf. https://mdavidsaver.github.io/p4p/building.html#build-as-python-package

**Comment by mdavidsaver** [comment]
The [numpy builds](https://pypi.org/project/numpy/#files) on linux for 3.9 have switch from building against `manylinux1` to `manylinux2010`.  I think this will require a new set of `epicscorelibs` builds first.

**Comment by mdavidsaver** [comment]
You could also try to install the newly built [`3.5.4a1`](https://pypi.org/project/p4p/3.5.4a1/#files), which includes py3.9 binaries.

```sh
python -m pip uninstall p4p
python -m pip uninstall epicscorelibs
python -m pip install p4p==3.5.4a1
python -m nose -v p4p
```

**Comment by mrkraimer** [comment]
I did the following:

    sudo pip uninstall p4p epicscorelibs
    sudo pip install p4p==3.5.4a1

Now it  works!!
Thanks.

I will close this issue
