### ISSUE TITLE
How to add Units on server?

### ISSUE THREAD

**Issue by jherkenhoff** [mdavidsaver/p4p#89]
Dear p4p developers,

can you quickly explain how to specify the "Units" field on a PV when setting up a server?

Best regards

**Comment by mdavidsaver** [comment]
You can `post()` a dict to bypass any NT type "wrapper", and change any field.

```py
from p4p.server.thread import SharedPV
from p4p.nt import NTScalar
pv=SharedPV()
pv.open(0, nt=NTScalar('i', display=True))

pv.post({'display.units':'arb.'})

print(pv.current().raw.tolist())
```
Prints:

```
[('value', 0),
 ('alarm', [('severity', 0), ('status', 0), ('message', '')]),
 ('timeStamp', [('secondsPastEpoch', 0), ('nanoseconds', 0), ('userTag', 0)]),
 ('display',
  [('limitLow', 0),
   ('limitHigh', 0),
   ('description', ''),
   ('format', ''),
   ('units', 'arb.')])]
```

**Comment by jherkenhoff** [comment]
Thanks for your fast and detailed response.
Do you mind if I add this to the documentation?
Are there plans on adding "pythonic" support for units? (And. limits etc,?)

**Comment by mdavidsaver** [comment]
> Do you mind if I add this to the documentation?

Not at all.  Added documentation is welcomed.

> Are there plans on adding "pythonic" support for units? (And. limits etc,?)

I'm not sure what "pythonic" means in this context.  Posting a dictionary will remain an "escape hatch" to go around whatever limitations the relevant `NT*` helper has.
