### ISSUE TITLE
non-unique Put operation

### ISSUE THREAD

**Issue by mdalesio** [mdavidsaver/p4p#9]
When running performance tests running loops of Put operations, I received the following error a number of times:

>> Provider pva for pv:in gives non-unique Put operation.  use_count=3

**Comment by mdavidsaver** [comment]
These warnings are removed with 98f35ca6058394e211a8dd3d839650017fcb679e.  The newer ```p4p.listRefs()``` and along with ```weak.ref``` and ```gc.collect()``` at the preferred tools for
detecting ref leaks.
