### ISSUE TITLE
other parameters  and return value for callback function in monitor

### ISSUE THREAD

**Issue by granrothge** [mdavidsaver/p4p#95]
I am using a callback function in monitor method of a pva context. I would like to pass some additional parameters to configure the call back.  Is there a reason not to add the ability to pass keyword arguments through in the monitor? Also add a callback return attribute to the monitor instance? So Syntax would be something kind of like the code snipet below.

I could definitely submit a pull request for the callback additional parameters.  I'm not so sure this is the best way of doing the function return.  Nevertheless I wanted to check if this is consistent with the development direction of the code before digging in too much.

```
import numpy as np
def cb(V,tlow=0,thigh=10):
   out=None
   tbool = (V['time_of_flight'].value >tlow-t_win) & (V['time_of_flight'].value <thigh) 
   out = V['time_of_flight'].value[tbool]
   return(out)   


pva = Context('pva')
mh = pva.monitor('foo',cb, callback_kw = {'tlow':0,'thigh':50})
print (mh.callback_out)
```

**Comment by granrothge** [comment]
I am fine with using partial. I agree it makes things clearer than a custom name or just adding a **kwargs.

**Comment by granrothge** [comment]
any thoughts on the return value from the callback?  I am currently using a global variable, which does not seem like the best solution.

**Comment by mdavidsaver** [comment]
> any thoughts on the return value from the callback?

Currently the value returned by a subscription callback is ignored.  I'm not clear on what else to do.  So I take your question to be more about how to communicate between the many invocations of a subscription callback.  My first suggestion would be to use an object, and pass a bound method as the callback.

```py
class X:
    def __init__(self):
        self.prev = None
    def cb(self, V):
        if self.prev is not None:
            print('diff', V-self.prev)
        self.prev = V
x = X()
mh = pva.monitor('foo', x.cb)
```

This can sometimes seem too "heavy" for me, so I sometimes do:

```py
prev = [None]
def cb(V, prev=prev):
        if prev[0] is not None:
            print('diff', V-prev[0])
        prev[0] = V
...
```

Or with python 3.x, a [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#nonlocal) might be even shorter.

**Comment by granrothge** [comment]
Sorry it has taken me awhile to get back to this.  I like the class approach I think it is the cleanest for both passing parameters in and data out.
